require("lazy").setup(
  {
    require("plugins.neo-tree"),
    require("plugins.nvim-treesitter"),
    require("plugins.vim-perl"),
    require("plugins.cmp"),
    require("plugins.neoformat"),
    require("plugins.null-ls"),
    require("plugins.heirline"),
    require("plugins.editorconfig")
  }
)
