---
name: Lua test for dotnvim v3

on:
  pull_request:
    paths:
      - ".github/workflows/dotnvim-test.yml"
      - "colors/**"
      - "lua/**"
      - "spec/**"
  push:
    branches:
      - main

jobs:
  lua-test:
    runs-on: ubuntu-latest
    steps:
      # runner environment
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      # setup nvim
      - uses: rhysd/action-setup-vim@7637152cb4a42c6e7c53ce5c728ca742b8ab0a6a # v1.3.3
        with:
          neovim: true
          version: v0.9.5

      # setup lua
      - uses: leafo/gh-actions-lua@35bcb06abec04ec87df82e08caa84d545348536e # v10.0.0
        with:
          luaVersion: 5.1.5
      - uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # v4.3.0
        with:
          lualocksVersion: 3.9.1

      # setup test environment
      - name: install vusted
        run: luarocks --lua-version=5.1 install vusted
 
      - name: test nvim dotfiles
        run: vusted
