---
name: Lua test for dotnvim v3

on:
  pull_request:
    paths:
      - ".github/workflows/dotnvim-test.yml"
      - "colors/**"
      - "lua/**"
      - "spec/**"
  push:
    branches:
      - main

jobs:
  lua-test:
    runs-on: ubuntu-latest
    steps:
      # runner environment
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      # setup nvim
      - uses: rhysd/action-setup-vim@2ab97f992520b094d4243cde0d3173493c811799 # v1.3.4
        with:
          neovim: true
          version: v0.9.5

      # setup plenary.nvim
      - name: setup plenary.nvim
        run: |
          set -euo pipefail

          export HEAD=a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683
          export CWD=$(pwd)

          mkdir -p ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          cd ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git init
          git remote add origin https://github.com/nvim-lua/plenary.nvim.git
          git fetch --depth 1 origin $HEAD
          git reset --hard $HEAD

      # run tests
      - name: run tests for kalaclista
        run: |
          ls -lah $(pwd)
          nvim --help
          nvim --headless --noplugin -u tests/init.vim -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/init.vim'}"
