---
name: Lua test for dotnvim v3

on:
  pull_request:
    paths:
      - ".github/workflows/dotnvim-test.yml"
      - "colors/**"
      - "lua/**"
      - "spec/**"
  push:
    branches:
      - main

jobs:
  lua-test:
    runs-on: ubuntu-latest
    steps:
      # runner environment
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      # setup nvim
      - uses: rhysd/action-setup-vim@0aa9cbac67d0fe3c5e3cde29caf745a721b19479 # v1.3.1
        with:
          neovim: true
          version: v0.9.5

      # setup lua
      - uses: leafo/gh-actions-lua@35bcb06abec04ec87df82e08caa84d545348536e # v10.0.0
        with:
          luaVersion: 5.1.5
      - uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # v4.3.0
        with:
          lualocksVersion: 3.9.1

      # setup test environment
      - name: install vusted
        run: luarocks --lua-version=5.1 install vusted
 
      - name: test nvim dotfiles
        run: vusted
